import {Client} from 'pg';
import {config} from '../config.js';

const META_TABLE = 'nodes_migration_meta';

function connectionString() {
  return process.env.DATABASE_URL || config.db.url;
}

function logStep(message: string) {
  process.stdout.write(`${message}\n`);
}

async function tableExists(client: Client, tableName: string) {
  const result = await client.query(
    `select exists (
       select 1
       from information_schema.tables
       where table_schema = 'public'
         and table_name = $1
     ) as ok`,
    [tableName],
  );
  return !!result.rows[0]?.ok;
}

async function columnExists(client: Client, tableName: string, columnName: string) {
  const result = await client.query(
    `select exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = $1
         and column_name = $2
     ) as ok`,
    [tableName, columnName],
  );
  return !!result.rows[0]?.ok;
}

async function scalarInt(client: Client, sql: string) {
  const result = await client.query(sql);
  return Number(result.rows[0]?.value || 0);
}

async function ensureLegacySchema(client: Client) {
  const hasRooms = await tableExists(client, 'rooms');
  const hasMessages = await tableExists(client, 'messages');
  const hasRoomId = hasMessages ? await columnExists(client, 'messages', 'room_id') : false;

  if (!hasRooms || !hasMessages || !hasRoomId) {
    throw new Error('legacy_schema_not_detected');
  }
}

async function alreadyMigrated(client: Client) {
  const hasMeta = await tableExists(client, META_TABLE);
  if (hasMeta) return true;

  const hasNodes = await tableExists(client, 'nodes');
  const hasLegacyRoomId = hasNodes ? await columnExists(client, 'messages', 'room_id') : false;
  return hasNodes && !hasLegacyRoomId;
}

async function renameLegacyTables(client: Client) {
  const tables = [
    'rooms',
    'messages',
    'rooms_users',
    'message_reactions',
    'game_sessions',
    'game_session_players',
  ];

  for (const tableName of tables) {
    const exists = await tableExists(client, tableName);
    if (!exists) continue;
    await client.query(`alter table "${tableName}" rename to "${tableName}_legacy"`);
  }
}

async function createNewSchema(client: Client) {
  await client.query(`
    create table nodes (
      id integer generated by default as identity primary key,
      parent_id integer references nodes(id) on delete cascade,
      type varchar(64) not null,
      component varchar(160),
      client_script varchar(160),
      server_script varchar(160),
      data jsonb not null default '{}'::jsonb,
      created_by integer references users(id) on delete set null,
      created_at timestamptz(3) not null default now()
    )
  `);

  await client.query(`
    create table rooms (
      id integer primary key references nodes(id) on delete cascade,
      kind varchar(64) not null,
      title text,
      pinned_node_id integer references nodes(id) on delete set null
    )
  `);

  await client.query(`
    create table messages (
      id integer primary key references nodes(id) on delete cascade,
      sender_id integer references users(id) on delete set null,
      kind varchar(64) not null,
      raw_text text not null,
      rendered_html text not null,
      created_at timestamptz(3) not null default now()
    )
  `);

  await client.query(`
    create table rooms_users (
      room_id integer not null references rooms(id) on delete cascade,
      user_id integer not null references users(id) on delete cascade,
      joined_at timestamptz(3) not null default now(),
      primary key (room_id, user_id)
    )
  `);

  await client.query(`
    create table message_reactions (
      id integer generated by default as identity primary key,
      message_id integer not null references messages(id) on delete cascade,
      user_id integer not null references users(id) on delete cascade,
      reaction varchar(32) not null,
      created_at timestamptz(3) not null default now(),
      unique (message_id, user_id)
    )
  `);

  await client.query(`
    create table game_sessions (
      id integer generated by default as identity primary key,
      room_id integer not null references rooms(id) on delete cascade,
      module_key varchar(64) not null,
      status "GameSessionStatus" not null,
      visibility "GameSessionVisibility" not null,
      created_by integer references users(id) on delete set null,
      created_at timestamptz(3) not null default now(),
      started_at timestamptz(3),
      finished_at timestamptz(3),
      settings_json jsonb not null,
      state_json jsonb not null
    )
  `);

  await client.query(`
    create table game_session_players (
      session_id integer not null references game_sessions(id) on delete cascade,
      user_id integer not null references users(id) on delete cascade,
      seat integer not null,
      kind "GameSessionPlayerKind" not null,
      joined_at timestamptz(3) not null default now(),
      is_ready boolean not null default true,
      primary key (session_id, user_id)
    )
  `);

  await client.query(`create unique index game_session_players_session_seat_key on game_session_players(session_id, seat)`);
  await client.query(`create index nodes_parent_idx on nodes(parent_id)`);
  await client.query(`create index nodes_type_idx on nodes(type)`);
  await client.query(`create index nodes_parent_type_id_desc_idx on nodes(parent_id, type, id desc)`);
  await client.query(`create index rooms_kind_idx on rooms(kind)`);
  await client.query(`create index rooms_pinned_node_idx on rooms(pinned_node_id)`);
  await client.query(`create index rooms_users_user_idx on rooms_users(user_id)`);
  await client.query(`create index messages_sender_idx on messages(sender_id)`);
  await client.query(`create index messages_created_desc_idx on messages(created_at desc)`);
  await client.query(`create index message_reactions_message_idx on message_reactions(message_id, reaction)`);
  await client.query(`create index game_sessions_room_idx on game_sessions(room_id)`);
  await client.query(`create index game_sessions_module_status_idx on game_sessions(module_key, status)`);
  await client.query(`create index game_session_players_user_idx on game_session_players(user_id)`);
}

async function migrateData(client: Client) {
  await client.query(`create temp table room_id_map (old_room_id integer primary key, new_node_id integer not null) on commit drop`);
  await client.query(`create temp table message_id_map (old_message_id integer primary key, new_node_id integer not null) on commit drop`);

  logStep('Migrating room nodes...');
  await client.query(`
    with source as (
      select
        r.*,
        row_number() over (order by r.id asc) as rn,
        case
          when r.script_id is not null and btrim(r.script_id) <> '' then lower(btrim(r.script_id))
          else null
        end as client_script_value,
        case
          when r.script_mode::text = 'client_server'
            and r.script_id is not null
            and btrim(r.script_id) <> ''
          then lower(btrim(r.script_id))
          else null
        end as server_script_value,
        jsonb_strip_nulls(
          jsonb_build_object(
            'scriptMode',
            case
              when r.script_id is not null and btrim(r.script_id) <> '' and r.script_mode is not null
              then r.script_mode::text
              else null
            end,
            'scriptRevision',
            case
              when coalesce(r.script_revision, 0) > 0 then r.script_revision
              else null
            end,
            'scriptConfig',
            coalesce(r.script_config_json, '{}'::jsonb),
            'scriptState',
            coalesce(r.script_state_json, '{}'::jsonb),
            'roomApp',
            case
              when coalesce(r.app_enabled, false)
                or r.app_type is not null
                or coalesce(r.app_config_json, '{}'::jsonb) <> '{}'::jsonb
              then jsonb_build_object(
                'enabled', coalesce(r.app_enabled, false),
                'type', r.app_type::text,
                'config', coalesce(r.app_config_json, '{}'::jsonb)
              )
              else null
            end
          )
        ) as node_data
      from rooms_legacy r
    ),
    inserted as (
      insert into nodes (parent_id, type, component, client_script, server_script, data, created_by, created_at)
      select
        null,
        'room',
        null,
        source.client_script_value,
        source.server_script_value,
        coalesce(source.node_data, '{}'::jsonb),
        source.created_by,
        coalesce(source.created_at, now())
      from source
      order by source.rn
      returning id
    ),
    numbered as (
      select id, row_number() over (order by id asc) as rn
      from inserted
    )
    insert into room_id_map (old_room_id, new_node_id)
    select source.id, numbered.id
    from source
    join numbered using (rn)
  `);

  logStep('Migrating message nodes...');
  await client.query(`
    with source as (
      select
        m.*,
        row_number() over (order by m.id asc) as rn,
        case
          when m.script_id is not null and btrim(m.script_id) <> '' then lower(btrim(m.script_id))
          else null
        end as client_script_value,
        case
          when m.script_mode::text = 'client_server'
            and m.script_id is not null
            and btrim(m.script_id) <> ''
          then lower(btrim(m.script_id))
          else null
        end as server_script_value,
        jsonb_strip_nulls(
          jsonb_build_object(
            'scriptMode',
            case
              when m.script_id is not null and btrim(m.script_id) <> '' and m.script_mode is not null
              then m.script_mode::text
              else null
            end,
            'scriptRevision',
            case
              when coalesce(m.script_revision, 0) > 0 then m.script_revision
              else null
            end,
            'scriptConfig',
            coalesce(m.script_config_json, '{}'::jsonb),
            'scriptState',
            coalesce(m.script_state_json, '{}'::jsonb)
          )
        ) as node_data
      from messages_legacy m
    ),
    inserted as (
      insert into nodes (parent_id, type, component, client_script, server_script, data, created_by, created_at)
      select
        room_map.new_node_id,
        'message',
        null,
        source.client_script_value,
        source.server_script_value,
        coalesce(source.node_data, '{}'::jsonb),
        source.sender_id,
        coalesce(source.created_at, now())
      from source
      join room_id_map room_map on room_map.old_room_id = source.room_id
      order by source.rn
      returning id
    ),
    numbered as (
      select id, row_number() over (order by id asc) as rn
      from inserted
    )
    insert into message_id_map (old_message_id, new_node_id)
    select source.id, numbered.id
    from source
    join numbered using (rn)
  `);

  logStep('Migrating rooms table...');
  await client.query(`
    insert into rooms (id, kind, title, pinned_node_id)
    select
      room_map.new_node_id,
      case
        when exists (
          select 1
          from messages_legacy discussion_source
          where discussion_source.discussion_room_id = legacy_room.id
        ) then 'comment'
        else legacy_room.kind::text
      end,
      legacy_room.title,
      pinned_map.new_node_id
    from rooms_legacy legacy_room
    join room_id_map room_map on room_map.old_room_id = legacy_room.id
    left join message_id_map pinned_map on pinned_map.old_message_id = legacy_room.pinned_message_id
  `);

  logStep('Migrating messages table...');
  await client.query(`
    insert into messages (id, sender_id, kind, raw_text, rendered_html, created_at)
    select
      message_map.new_node_id,
      legacy_message.sender_id,
      legacy_message.kind::text,
      legacy_message.raw_text,
      legacy_message.rendered_html,
      coalesce(legacy_message.created_at, now())
    from messages_legacy legacy_message
    join message_id_map message_map on message_map.old_message_id = legacy_message.id
  `);

  logStep('Linking comment rooms under message nodes...');
  await client.query(`
    update nodes target
    set parent_id = message_map.new_node_id
    from messages_legacy legacy_message
    join room_id_map discussion_room_map on discussion_room_map.old_room_id = legacy_message.discussion_room_id
    join message_id_map message_map on message_map.old_message_id = legacy_message.id
    where legacy_message.discussion_room_id is not null
      and target.id = discussion_room_map.new_node_id
  `);

  logStep('Migrating room memberships...');
  await client.query(`
    insert into rooms_users (room_id, user_id, joined_at)
    select
      room_map.new_node_id,
      legacy_membership.user_id,
      coalesce(legacy_membership.joined_at, now())
    from rooms_users_legacy legacy_membership
    join room_id_map room_map on room_map.old_room_id = legacy_membership.room_id
  `);

  logStep('Migrating reactions...');
  await client.query(`
    insert into message_reactions (message_id, user_id, reaction, created_at)
    select
      message_map.new_node_id,
      legacy_reaction.user_id,
      legacy_reaction.reaction,
      coalesce(legacy_reaction.created_at, now())
    from message_reactions_legacy legacy_reaction
    join message_id_map message_map on message_map.old_message_id = legacy_reaction.message_id
  `);

  logStep('Migrating game sessions...');
  await client.query(`
    insert into game_sessions (
      id,
      room_id,
      module_key,
      status,
      visibility,
      created_by,
      created_at,
      started_at,
      finished_at,
      settings_json,
      state_json
    )
    select
      legacy_session.id,
      room_map.new_node_id,
      legacy_session.module_key,
      legacy_session.status,
      legacy_session.visibility,
      legacy_session.created_by,
      coalesce(legacy_session.created_at, now()),
      legacy_session.started_at,
      legacy_session.finished_at,
      legacy_session.settings_json,
      legacy_session.state_json
    from game_sessions_legacy legacy_session
    join room_id_map room_map on room_map.old_room_id = legacy_session.room_id
  `);

  logStep('Migrating game session players...');
  await client.query(`
    insert into game_session_players (session_id, user_id, seat, kind, joined_at, is_ready)
    select
      legacy_player.session_id,
      legacy_player.user_id,
      legacy_player.seat,
      legacy_player.kind,
      coalesce(legacy_player.joined_at, now()),
      coalesce(legacy_player.is_ready, true)
    from game_session_players_legacy legacy_player
  `);

  await client.query(`
    select
      setval(pg_get_serial_sequence('nodes', 'id'), coalesce((select max(id) from nodes), 1), true),
      setval(pg_get_serial_sequence('message_reactions', 'id'), coalesce((select max(id) from message_reactions), 1), true),
      setval(pg_get_serial_sequence('game_sessions', 'id'), coalesce((select max(id) from game_sessions), 1), true)
  `);
}

async function verifyCounts(client: Client) {
  const checks = [
    {
      name: 'rooms',
      expected: await scalarInt(client, `select count(*) as value from rooms_legacy`),
      actual: await scalarInt(client, `select count(*) as value from rooms`),
    },
    {
      name: 'messages',
      expected: await scalarInt(client, `select count(*) as value from messages_legacy`),
      actual: await scalarInt(client, `select count(*) as value from messages`),
    },
    {
      name: 'rooms_users',
      expected: await scalarInt(client, `select count(*) as value from rooms_users_legacy`),
      actual: await scalarInt(client, `select count(*) as value from rooms_users`),
    },
    {
      name: 'message_reactions',
      expected: await scalarInt(client, `select count(*) as value from message_reactions_legacy`),
      actual: await scalarInt(client, `select count(*) as value from message_reactions`),
    },
    {
      name: 'game_sessions',
      expected: await scalarInt(client, `select count(*) as value from game_sessions_legacy`),
      actual: await scalarInt(client, `select count(*) as value from game_sessions`),
    },
    {
      name: 'game_session_players',
      expected: await scalarInt(client, `select count(*) as value from game_session_players_legacy`),
      actual: await scalarInt(client, `select count(*) as value from game_session_players`),
    },
  ];

  for (const check of checks) {
    if (check.expected !== check.actual) {
      throw new Error(`count_mismatch:${check.name}:${check.expected}:${check.actual}`);
    }
  }
}

async function finalizeMigration(client: Client) {
  await client.query(`
    create table ${META_TABLE} (
      id integer generated by default as identity primary key,
      completed_at timestamptz(3) not null default now(),
      notes text not null
    )
  `);

  await client.query(
    `insert into ${META_TABLE} (notes) values ($1)`,
    ['legacy rooms/messages/graph migrated to canonical nodes tree'],
  );

  await client.query(`drop table if exists graph_edges cascade`);
  await client.query(`drop table if exists graph_nodes cascade`);
  await client.query(`drop table rooms_users_legacy cascade`);
  await client.query(`drop table message_reactions_legacy cascade`);
  await client.query(`drop table game_session_players_legacy cascade`);
  await client.query(`drop table game_sessions_legacy cascade`);
  await client.query(`drop table messages_legacy cascade`);
  await client.query(`drop table rooms_legacy cascade`);
  await client.query(`drop type if exists "GraphEdgeType"`);
  await client.query(`drop type if exists "GraphTargetType"`);
  await client.query(`drop type if exists "GraphNodeKind"`);
  await client.query(`drop type if exists "RoomAppType"`);
  await client.query(`drop type if exists "ScriptExecutionMode"`);
  await client.query(`drop type if exists "MessageKind"`);
  await client.query(`drop type if exists "RoomKind"`);
}

async function run() {
  const client = new Client({
    connectionString: connectionString(),
  });

  await client.connect();

  try {
    if (await alreadyMigrated(client)) {
      logStep('nodes migration already applied, nothing to do');
      return;
    }

    await ensureLegacySchema(client);

    await client.query('begin');
    await client.query(`set local lock_timeout = '10s'`);
    await client.query(`set local statement_timeout = '0'`);
    await client.query(`
      lock table
        rooms,
        messages,
        rooms_users,
        message_reactions,
        game_sessions,
        game_session_players
      in access exclusive mode
    `);

    logStep('Renaming legacy tables...');
    await renameLegacyTables(client);

    logStep('Creating new nodes schema...');
    await createNewSchema(client);

    await migrateData(client);
    await verifyCounts(client);
    await finalizeMigration(client);

    await client.query('commit');
    logStep('nodes migration completed successfully');
  } catch (error) {
    try {
      await client.query('rollback');
    } catch {
      // ignore rollback failure
    }
    throw error;
  } finally {
    await client.end();
  }
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
