ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_bot boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS info text;

ALTER TABLE users
  DROP CONSTRAINT IF EXISTS users_nickname_format_check;

ALTER TABLE users
  ADD CONSTRAINT users_nickname_format_check
  CHECK (nickname ~ '^!?[a-z0-9_-]{3,32}$');

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'RoomKind') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_enum e
      JOIN pg_type t ON t.oid = e.enumtypid
      WHERE t.typname = 'RoomKind'
        AND e.enumlabel = 'game'
    ) THEN
      ALTER TYPE "RoomKind" ADD VALUE 'game';
    END IF;
  ELSE
    CREATE TYPE "RoomKind" AS ENUM ('group', 'direct', 'game');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GameSessionStatus') THEN
    CREATE TYPE "GameSessionStatus" AS ENUM ('lobby', 'active', 'finished', 'cancelled');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GameSessionVisibility') THEN
    CREATE TYPE "GameSessionVisibility" AS ENUM ('solo', 'public', 'invite_only');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'GameSessionPlayerKind') THEN
    CREATE TYPE "GameSessionPlayerKind" AS ENUM ('human', 'bot');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS game_sessions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id       integer NOT NULL,
  module_key    varchar(64) NOT NULL,
  status        "GameSessionStatus" NOT NULL,
  visibility    "GameSessionVisibility" NOT NULL,
  created_by    integer,
  created_at    timestamptz(3) NOT NULL DEFAULT now(),
  started_at    timestamptz(3),
  finished_at   timestamptz(3),
  settings_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  state_json    jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT game_sessions_room_id_fkey
    FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT game_sessions_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS game_sessions_room_idx
  ON game_sessions(room_id);

CREATE INDEX IF NOT EXISTS game_sessions_module_status_idx
  ON game_sessions(module_key, status);

CREATE TABLE IF NOT EXISTS game_session_players (
  session_id integer NOT NULL,
  user_id    integer NOT NULL,
  seat       integer NOT NULL,
  kind       "GameSessionPlayerKind" NOT NULL,
  joined_at  timestamptz(3) NOT NULL DEFAULT now(),
  is_ready   boolean NOT NULL DEFAULT true,
  CONSTRAINT game_session_players_pkey PRIMARY KEY (session_id, user_id),
  CONSTRAINT game_session_players_session_seat_key UNIQUE (session_id, seat),
  CONSTRAINT game_session_players_session_id_fkey
    FOREIGN KEY (session_id) REFERENCES game_sessions(id) ON DELETE CASCADE,
  CONSTRAINT game_session_players_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS game_session_players_user_idx
  ON game_session_players(user_id);
