BEGIN;

-- Safety guards: migration is for old schema with dialogs/messages.dialog_id
DO $$
BEGIN
  IF to_regclass('public.dialogs') IS NULL THEN
    RAISE EXCEPTION 'Table public.dialogs not found. Migration expects old schema.';
  END IF;

  IF to_regclass('public.messages') IS NULL THEN
    RAISE EXCEPTION 'Table public.messages not found.';
  END IF;

  IF to_regclass('public.rooms') IS NOT NULL THEN
    RAISE EXCEPTION 'Table public.rooms already exists. Migration looks already applied.';
  END IF;
END
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM dialogs
    WHERE kind::text NOT IN ('general', 'private')
  ) THEN
    RAISE EXCEPTION 'Found unsupported dialogs.kind values. Abort migration.';
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'RoomKind') THEN
    CREATE TYPE "RoomKind" AS ENUM ('group', 'direct');
  END IF;
END
$$;

CREATE TABLE rooms (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind       "RoomKind" NOT NULL,
  title      TEXT,
  created_by INTEGER,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT rooms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX rooms_kind_idx ON rooms(kind);

CREATE TABLE rooms_users (
  room_id   INTEGER NOT NULL,
  user_id   INTEGER NOT NULL,
  joined_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT rooms_users_pkey PRIMARY KEY (room_id, user_id),
  CONSTRAINT rooms_users_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT rooms_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX rooms_users_user_idx ON rooms_users(user_id);

-- 1) dialogs -> rooms (preserve IDs)
INSERT INTO rooms (id, kind, title, created_by, created_at)
SELECT
  d.id,
  CASE d.kind::text
    WHEN 'general' THEN 'group'::"RoomKind"
    WHEN 'private' THEN 'direct'::"RoomKind"
  END AS kind,
  NULL::TEXT AS title,
  NULL::INTEGER AS created_by,
  d.created_at
FROM dialogs d;

DO $$
DECLARE
  max_id BIGINT;
  seq_name TEXT;
BEGIN
  SELECT pg_get_serial_sequence('rooms', 'id') INTO seq_name;
  SELECT max(id) INTO max_id FROM rooms;

  IF seq_name IS NOT NULL THEN
    IF max_id IS NULL THEN
      EXECUTE format('SELECT setval(%L, 1, false)', seq_name);
    ELSE
      EXECUTE format('SELECT setval(%L, %s, true)', seq_name, max_id);
    END IF;
  END IF;
END
$$;

-- 2) private dialogs participants -> direct rooms participants
INSERT INTO rooms_users (room_id, user_id, joined_at)
SELECT d.id, d.member_a, d.created_at
FROM dialogs d
WHERE d.kind::text = 'private' AND d.member_a IS NOT NULL
UNION ALL
SELECT d.id, d.member_b, d.created_at
FROM dialogs d
WHERE d.kind::text = 'private' AND d.member_b IS NOT NULL
ON CONFLICT (room_id, user_id) DO NOTHING;

-- 3) old general dialogs become regular group rooms with all existing users
INSERT INTO rooms_users (room_id, user_id, joined_at)
SELECT r.id, u.id, r.created_at
FROM rooms r
CROSS JOIN users u
WHERE r.kind = 'group'
ON CONFLICT (room_id, user_id) DO NOTHING;

-- 4) messages: repoint FK from dialogs to rooms and rename dialog_id -> room_id
DO $$
DECLARE
  missing_count BIGINT;
BEGIN
  SELECT count(*)
    INTO missing_count
  FROM messages m
  LEFT JOIN rooms r ON r.id = m.dialog_id
  WHERE r.id IS NULL;

  IF missing_count > 0 THEN
    RAISE EXCEPTION 'Found % messages without matching room after copy.', missing_count;
  END IF;
END
$$;

DO $$
DECLARE
  fk_name TEXT;
BEGIN
  FOR fk_name IN
    SELECT c.conname
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    JOIN pg_class rt ON rt.oid = c.confrelid
    WHERE n.nspname = 'public'
      AND t.relname = 'messages'
      AND c.contype = 'f'
      AND rt.relname = 'dialogs'
  LOOP
    EXECUTE format('ALTER TABLE messages DROP CONSTRAINT %I', fk_name);
  END LOOP;
END
$$;

ALTER TABLE messages RENAME COLUMN dialog_id TO room_id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'messages_dialog_created_idx'
  ) THEN
    ALTER INDEX messages_dialog_created_idx RENAME TO messages_room_created_idx;
  END IF;
END
$$;

ALTER TABLE messages
  ADD CONSTRAINT messages_room_id_fkey
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS messages_room_created_idx
  ON messages(room_id, created_at DESC);

-- 5) drop old structure
DROP TABLE dialogs;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'DialogKind') THEN
    DROP TYPE "DialogKind";
  END IF;
END
$$;

COMMIT;
