import {ref} from 'vue';
import type {Dialog, Message, User} from '@/composables/types';
import {wsConnectionState} from '@/composables/ws-rpc';
import type {DirectDialog, NotificationItem, ToastItem} from './chat-page.constants';
import type {ScriptRuntimeManager} from '@/scriptable/runtime/manager';

export function createChatPageState() {
  return {
    me: ref<User | null>(null),
    users: ref<User[]>([]),
    directDialogs: ref<DirectDialog[]>([]),
    pinnedDirectUserIds: ref<number[]>([]),
    generalDialog: ref<Dialog | null>(null),
    activeDialog: ref<Dialog | null>(null),

    messages: ref<Message[]>([]),
    activePinnedMessage: ref<Message | null>(null),
    pinnedCollapsed: ref(false),
    pinnedPanelHeightRatio: ref(0.24),
    pinnedSplitterDragState: ref<{
      startY: number;
      startRatio: number;
      containerHeight: number;
    } | null>(null),
    scriptRuntimeManager: ref<ScriptRuntimeManager | null>(null),
    scriptMessageViewModels: ref<Record<number, Record<string, any>>>({}),
    activeRoomScript: ref<any | null>(null),
    activeRoomScriptViewModel: ref<Record<string, any> | null>(null),
    messageText: ref(''),
    composerToolsOpen: ref(false),
    composerColorPicker: ref('#61afef'),
    composerSelectionStart: ref(0),
    composerSelectionEnd: ref(0),
    editingMessageId: ref<number | null>(null),
    editingMessageText: ref(''),
    messageActionPendingId: ref<number | null>(null),
    discussionOpenPendingMessageId: ref<number | null>(null),
    error: ref(''),
    historyLoading: ref(false),
    historyLoadingMore: ref(false),
    historyHasMore: ref(true),
    historyLoadSeq: ref(0),
    virtualMessageHeights: ref<Record<number, number>>({}),
    virtualPrefixHeights: ref<number[]>([0]),
    virtualTotalHeight: ref(0),
    virtualRangeStart: ref(0),
    virtualRangeEnd: ref(0),
    virtualSyncScheduled: ref(false),
    messagesEl: ref<HTMLDivElement | null>(null),
    chatContentEl: ref<HTMLDivElement | null>(null),
    messageInputEl: ref<HTMLTextAreaElement | null>(null),
    galleryInputEl: ref<HTMLInputElement | null>(null),
    showScrollDown: ref(false),
    forceOwnScrollDown: ref(false),
    pendingAnonymousOwnMessage: ref<{
      roomId: number;
      messageId: number;
      createdAt: number;
    } | null>(null),
    freshMessageIds: ref<Record<number, true>>({}),
    freshMessageTimers: ref<Record<number, number>>({}),
    blinkMessageId: ref<number | null>(null),
    blinkTimer: ref<number | null>(null),
    timeTooltipVisible: ref(false),
    timeTooltipText: ref(''),
    timeTooltipX: ref(0),
    timeTooltipY: ref(0),
    reactionTooltipVisible: ref(false),
    reactionTooltipText: ref(''),
    reactionTooltipX: ref(0),
    reactionTooltipY: ref(0),
    reactionPickerMessageId: ref<number | null>(null),
    imageViewerVisible: ref(false),
    imageViewerSrc: ref(''),
    imageViewerAlt: ref(''),
    imageViewerBodyOverflow: ref<string | null>(null),
    faviconBlinkTimer: ref<number | null>(null),
    faviconBlinkAlertFrame: ref(false),
    inactiveTabUnread: ref(false),
    windowFocused: ref(true),
    documentVisible: ref(true),

    leftMenuOpen: ref(false),
    rightMenuOpen: ref(false),
    isCompactLayout: ref(false),
    leftNavMode: ref<'directs' | 'rooms'>('directs'),
    searchQuery: ref(''),
    roomSearchQuery: ref(''),
    joinedRooms: ref<Dialog[]>([]),
    publicRooms: ref<Dialog[]>([]),
    roomCreateTitle: ref(''),
    roomCreateVisibility: ref<'public' | 'private'>('public'),
    roomCreateCommentsEnabled: ref(true),
    roomCreating: ref(false),
    roomInviteOpen: ref(false),
    roomInviteLoading: ref(false),
    roomInviteError: ref(''),
    roomInviteSearchQuery: ref(''),
    roomInviteContacts: ref<User[]>([]),
    roomInviteSelectedIds: ref<number[]>([]),
    notificationsMenuOpen: ref(false),
    notifications: ref<NotificationItem[]>([]),
    notificationsSeq: ref(1),
    badgeNowTs: ref(Date.now()),
    badgeTickTimer: ref<number | null>(null),
    handledMessageNotificationIds: ref<Record<number, true>>({}),
    handledMessageNotificationSaveTimer: ref<number | null>(null),
    notificationMenuEl: ref<HTMLElement | null>(null),
    notificationButtonEl: ref<HTMLElement | null>(null),
    windowClickHandler: ref<Function | null>(null),
    toasts: ref<ToastItem[]>([]),
    toastTimerById: ref<Record<number, number>>({}),

    profileName: ref(''),
    profileNicknameColor: ref(''),
    profileColorPicker: ref('#61afef'),
    profileSaving: ref(false),
    profileError: ref(''),
    roomDeletePending: ref(false),
    navPinPending: ref(false),
    soundEnabled: ref(true),
    vibrationEnabled: ref(true),
    soundOverlayVisible: ref(false),
    soundReady: ref(false),
    notificationAudioEl: ref<HTMLAudioElement | null>(null),
    browserNotificationsEnabled: ref(true),
    browserNotificationPermission: ref<'default' | 'denied' | 'granted'>('default'),
    activeBrowserNotifications: ref<Notification[]>([]),
    webPushSupported: ref(false),
    webPushAvailable: ref(false),
    webPushSettingEnabled: ref(true),
    webPushEnabled: ref(false),
    webPushSynced: ref(false),
    webPushBusy: ref(false),
    webPushTestBusy: ref(false),
    webPushPermission: ref<'default' | 'denied' | 'granted'>('default'),
    webPushError: ref(''),
    webPushTestStatus: ref(''),
    webPushDiagnosticLines: ref<string[]>([]),
    webPushVapidPublicKey: ref(''),
    webPushRequiresIosInstall: ref(false),
    pushDisableAllMentions: ref(false),
    routeSyncReady: ref(false),
    wsConnectionState,

    newPassword: ref(''),
    pasteUploading: ref(false),
    sendAnonymous: ref(false),

    chatMessageHandler: ref<Function | null>(null),
    chatMessageUpdatedHandler: ref<Function | null>(null),
    chatMessageDeletedHandler: ref<Function | null>(null),
    chatPinnedHandler: ref<Function | null>(null),
    chatRoomUpdatedHandler: ref<Function | null>(null),
    chatReactionsHandler: ref<Function | null>(null),
    dialogsDeletedHandler: ref<Function | null>(null),
    chatReactionNotifyHandler: ref<Function | null>(null),
    chatCommentNotifyHandler: ref<Function | null>(null),
    scriptsStateHandler: ref<Function | null>(null),
    usersUpdatedHandler: ref<Function | null>(null),
    disconnectedHandler: ref<Function | null>(null),
    reconnectedHandler: ref<Function | null>(null),
    sessionExpiredHandler: ref<Function | null>(null),
    windowKeydownHandler: ref<Function | null>(null),
    windowResizeHandler: ref<Function | null>(null),
    windowFocusHandler: ref<Function | null>(null),
    windowBlurHandler: ref<Function | null>(null),
    visibilityChangeHandler: ref<Function | null>(null),
    pinnedSplitterPointerMoveHandler: ref<Function | null>(null),
    pinnedSplitterPointerUpHandler: ref<Function | null>(null),
  };
}
