<template>
  <div class="page page-console">
    <div class="console-shell">
      <ConsoleTopbar @back="goBack" />
      <ConsoleTabs
        :active-tab="activeTab"
        :console-user-tab-label="consoleUserTabLabel"
        @set-active-tab="setActiveTab"
      />

      <div v-if="loading" class="console-card">
        <div class="hint">Загрузка...</div>
      </div>
      <div v-else-if="error" class="console-card">
        <div class="error">{{ error }}</div>
      </div>
      <template v-else>
        <ProfileTab
          v-if="activeTab === 'user'"
          :browser-notification-permission="browserNotificationPermission"
          :browser-notifications-enabled="browserNotificationsEnabled"
          :can-send-web-push-test="canSendWebPushTest"
          :contact-busy="contactBusy"
          :has-donation-badge="hasDonationBadge"
          :is-contact="isContact"
          :is-dev-mode="isDevMode"
          :is-own-profile="isOwnProfile"
          :is-standalone-app="isStandaloneApp"
          :is-system-nickname="isSystemNickname"
          :new-password="newPassword"
          :profile="profile"
          :profile-color-picker="profileColorPicker"
          :profile-display-avatar-url="profileDisplayAvatarUrl"
          :profile-display-name="profileDisplayName"
          :profile-display-nickname-color="profileDisplayNicknameColor"
          :profile-info="profileInfo"
          :profile-name="profileName"
          :profile-nickname-color="profileNicknameColor"
          :push-disable-all-mentions="pushDisableAllMentions"
          :save-error="saveError"
          :save-success="saveSuccess"
          :saving="saving"
          :sound-enabled="soundEnabled"
          :user-avatar-fallback="userAvatarFallback"
          :vibration-enabled="vibrationEnabled"
          :web-push-available="webPushAvailable"
          :web-push-busy="webPushBusy"
          :web-push-error="webPushError"
          :web-push-requires-ios-install="webPushRequiresIosInstall"
          :web-push-setting-enabled="webPushSettingEnabled"
          :web-push-status-text="webPushStatusText"
          :web-push-supported="webPushSupported"
          :web-push-test-busy="webPushTestBusy"
          :web-push-test-status="webPushTestStatus"
          @avatar-change="onProfileAvatarInputChange"
          @browser-notifications-change="onBrowserNotificationsEnabledChange"
          @clear-nickname-color="clearNicknameColor"
          @color-picked="onColorPicked"
          @media-open="openMediaViewer"
          @request-browser-permission="requestBrowserNotificationPermission"
          @save-profile="onSaveProfile"
          @send-web-push-test="sendWebPushTest"
          @sound-change="onSoundEnabledChange"
          @toggle-contact="toggleContact"
          @update:browser-notifications-enabled="browserNotificationsEnabled = $event"
          @update:new-password="newPassword = $event"
          @update:profile-color-picker="profileColorPicker = $event"
          @update:profile-info="profileInfo = $event"
          @update:profile-name="profileName = $event"
          @update:push-disable-all-mentions="pushDisableAllMentions = $event"
          @update:sound-enabled="soundEnabled = $event"
          @update:vibration-enabled="vibrationEnabled = $event"
          @update:web-push-setting-enabled="webPushSettingEnabled = $event"
          @vibration-change="onVibrationEnabledChange"
          @web-push-change="onWebPushEnabledChange"
          @write-to-user="onWriteToUser"
        />

        <RoomsTab
          v-else-if="activeTab === 'rooms'"
          :can-edit-selected-room="canEditSelectedRoom"
          :can-kick-room-member="canKickRoomMember"
          :can-leave-selected-room="canLeaveSelectedRoom"
          :is-own-profile="isOwnProfile"
          :is-room-member-action-busy="isRoomMemberActionBusy"
          :is-system-nickname="isSystemNickname"
          :resolve-media-url="resolveMediaUrl"
          :resolve-room-avatar-url="resolveRoomAvatarUrl"
          :resolve-user-avatar-url="resolveUserAvatarUrl"
          :room-avatar-fallback="roomAvatarFallback"
          :room-comments-enabled="roomCommentsEnabled"
          :room-create-avatar-path="roomCreateAvatarPath"
          :room-create-comments-enabled="roomCreateCommentsEnabled"
          :room-create-form-open="roomCreateFormOpen"
          :room-create-post-only-by-admin="roomCreatePostOnlyByAdmin"
          :room-create-title="roomCreateTitle"
          :room-create-visibility="roomCreateVisibility"
          :room-creating="roomCreating"
          :room-delete-busy="roomDeleteBusy"
          :room-leave-busy="roomLeaveBusy"
          :room-members-loading="roomMembersLoading"
          :room-post-only-by-admin="roomPostOnlyByAdmin"
          :room-save-error="roomSaveError"
          :room-save-success="roomSaveSuccess"
          :room-saving="roomSaving"
          :room-title="roomTitle"
          :room-visibility="roomVisibility"
          :rooms-loading="roomsLoading"
          :rooms-tab-list="roomsTabList"
          :rooms-tab-owner-label="roomsTabOwnerLabel"
          :selected-room="selectedRoom"
          :selected-room-display-avatar-url="selectedRoomDisplayAvatarUrl"
          :selected-room-display-title="selectedRoomDisplayTitle"
          :sorted-room-members="sortedRoomMembers"
          :user-avatar-fallback="userAvatarFallback"
          @create-room="onCreateRoom"
          @create-room-avatar-change="onCreateRoomAvatarInputChange"
          @delete-room="onDeleteRoom"
          @go-own-rooms-for-create="onGoOwnRoomsForCreate"
          @kick-room-member="onKickRoomMember"
          @leave-selected-room="onLeaveSelectedRoom"
          @media-open="openMediaViewer"
          @open-room-member-profile="onOpenRoomMemberProfile"
          @open-room-tab="openRoomTab"
          @room-avatar-change="onRoomAvatarInputChange"
          @save-room="onSaveRoom"
          @toggle-create-form="toggleRoomCreateForm"
          @update:room-comments-enabled="roomCommentsEnabled = $event"
          @update:room-create-comments-enabled="roomCreateCommentsEnabled = $event"
          @update:room-create-post-only-by-admin="roomCreatePostOnlyByAdmin = $event"
          @update:room-create-title="roomCreateTitle = $event"
          @update:room-create-visibility="roomCreateVisibility = $event"
          @update:room-post-only-by-admin="roomPostOnlyByAdmin = $event"
          @update:room-title="roomTitle = $event"
          @update:room-visibility="roomVisibility = $event"
        />

        <VpnTab
          v-else-if="activeTab === 'vpn'"
          :amnezia-file-android="amneziaFileAndroid"
          :amnezia-file-linux="amneziaFileLinux"
          :amnezia-file-mac-os="amneziaFileMacOs"
          :amnezia-file-windows="amneziaFileWindows"
          :copied-vpn-link="copiedVpnLink"
          :copy-vpn-error="copyVpnError"
          :download-href-android="downloadHrefAndroid"
          :download-href-linux="downloadHrefLinux"
          :download-href-mac-os="downloadHrefMacOs"
          :download-href-windows="downloadHrefWindows"
          :mt-proxy-deep-link="mtProxyDeepLink"
          :mt-proxy-web-link="mtProxyWebLink"
          :vpn-provision-error="vpnProvisionError"
          :vpn-provision-link="vpnProvisionLink"
          :vpn-provision-qr-data-url="vpnProvisionQrDataUrl"
          :vpn-provision-qr-error="vpnProvisionQrError"
          :vpn-provision-state="vpnProvisionState"
          @copy-vpn-link="copyVpnLink"
          @download-click="onDownloadClick"
          @request-vpn-provision="requestVpnProvision"
        />

        <InvitesTab
          v-else
          :invite-creating="inviteCreating"
          :invite-error="inviteError"
          :invite-rooms="inviteRooms"
          :invite-rooms-loading="inviteRoomsLoading"
          :invites="invites"
          :is-authed="isAuthed"
          :last-invite-link="lastInviteLink"
          :selected-invite-room-ids="selectedInviteRoomIds"
          @copy-invite-code="copyInviteCode"
          @copy-invite-link="copyInviteLink"
          @create-invite="onCreateInvite"
          @delete-invite="onDeleteInvite"
          @update:selected-invite-room-ids="selectedInviteRoomIds = $event"
        />

        <DonationCard
          :copied-donation-phone="copiedDonationPhone"
          :donation-action-error="donationActionError"
          :donation-bank="donationBank"
          :donation-button-text="donationButtonText"
          :donation-button-undo-mode="donationButtonUndoMode"
          :donation-phone="donationPhone"
          :vpn-info-error="vpnInfoError"
          :vpn-info-loading="vpnInfoLoading"
          @copy-donation-phone="copyDonationPhone"
          @donation-button-click="onDonationButtonClick"
        />
      </template>
    </div>

    <AvatarCropModal
      :avatar-crop-busy="avatarCropBusy"
      :avatar-crop-image-style="avatarCropImageStyle"
      :avatar-crop-max-scale="avatarCropMaxScale"
      :avatar-crop-min-scale="avatarCropMinScale"
      :avatar-crop-scale="avatarCropScale"
      :avatar-crop-scale-percent="avatarCropScalePercent"
      :avatar-crop-source-url="avatarCropSourceUrl"
      :avatar-crop-visible="avatarCropVisible"
      @close="closeAvatarCropper"
      @finalize="finalizeAvatarCropAndUpload"
      @overlay-click="onAvatarCropOverlayClick"
      @pointer-down="onAvatarCropPointerDown"
      @scale-input="onAvatarCropScaleInput"
    />
    <ConsoleMediaViewer
      :media-viewer-alt="mediaViewerAlt"
      :media-viewer-src="mediaViewerSrc"
      :media-viewer-visible="mediaViewerVisible"
      @close="closeMediaViewer"
    />
    <ConsoleCopyToast
      :copy-toast-text="copyToastText"
      :copy-toast-visible="copyToastVisible"
    />
  </div>
</template>

<script src="./script.ts" lang="ts"/>
<style src="./style.less" lang="less"/>
